#Requires -Version 5.1
<#
.SYNOPSIS
    Generate Markdown test report from autotest_results.json
.PARAMETER ResultsPath
    Path to autotest_results.json
.PARAMETER ProjectDir
    Project root directory
#>
param(
    [string]$ResultsPath = "",
    [string]$ProjectDir = ""
)

$ErrorActionPreference = "Stop"

# ============================================
# Constants
# ============================================
$script:ResultsFileName = "autotest_results.json"
$script:ReportDirName = "Saved\Automation\Reports"
$script:TimestampFormatDisplay = "yyyy-MM-dd HH:mm:ss"
$script:TimestampFormatFile = "yyyy-MM-dd-HHmmss"
$script:ReportTitle = "# UE5 Automation Test Report"
$script:GeneratorCredit = "*Generated by ue-autotest skill*"
$script:DefaultLogHint = "Saved\Logs"

# ============================================
# 1. Resolve Results Path
# ============================================
function Resolve-ResultsPath {
    param([string]$ExplicitPath, [string]$ProjectDirectory)

    if ($ExplicitPath -and (Test-Path $ExplicitPath)) {
        return $ExplicitPath
    }

    $autoPath = Join-Path $ProjectDirectory "Saved\Automation\$script:ResultsFileName"
    if (Test-Path $autoPath) {
        return $autoPath
    }

    throw "Results file not found. Tried: $ExplicitPath, $autoPath"
}

# ============================================
# 2. Build Markdown Report
# ============================================
function Format-TestReport {
    param([PSCustomObject]$Data, [string]$ProjectDir)

    $parts = @()
    $parts += Format-ReportHeader -Data $Data -ProjectDir $ProjectDir
    $parts += Format-SummarySection -Overall $Data.overall

    foreach ($mod in $Data.modules) {
        $parts += Format-ModuleSection -Module $mod
    }

    $parts += Format-ReportFooter
    return $parts -join "`n"
}

function Format-ReportHeader {
    param([PSCustomObject]$Data, [string]$ProjectDir)

    $timestamp = Get-Date -Format $script:TimestampFormatDisplay
    $md = @()
    $md += $script:ReportTitle
    $md += ""
    $md += "- **Generated:** $timestamp"
    $md += "- **Project:** $(Split-Path $ProjectDir -Leaf)"
    $md += "- **Modules:** $($Data.modules.Count)"
    $md += ""
    return $md -join "`n"
}

function Format-SummarySection {
    param([PSCustomObject]$Overall)

    $total = $Overall.total
    $passed = $Overall.passed
    $failed = $Overall.failed
    $passRate = if ($total -gt 0) { [math]::Round(($passed / $total) * 100, 1) } else { 0 }

    $md = @()
    $md += "## Summary"
    $md += ""
    $md += "| Metric | Value |"
    $md += "|--------|-------|"
    $md += "| Total Tests | $total |"
    $md += "| Passed | $passed |"
    $md += "| Failed | $failed |"
    $md += "| Pass Rate | $passRate% |"
    $md += ""

    if ($failed -eq 0) {
        $md += "> All tests passed."
    } else {
        $md += "> **$failed test(s) failed.**"
    }
    $md += ""
    return $md -join "`n"
}

function Format-ReportFooter {
    $md = @()
    $md += "---"
    $md += ""
    $md += $script:GeneratorCredit
    $md += ""
    $md += "**Log files:** see each module section; default location is ``$script:DefaultLogHint``."
    $md += ""
    return $md -join "`n"
}

function Format-ModuleSection {
    param([PSCustomObject]$Module)

    $modTotal = $Module.results.summary.total
    $modPassed = $Module.results.summary.passed
    $modFailed = $Module.results.summary.failed

    $md = @()
    $md += "## Module: $($Module.name)"
    $md += ""
    $md += "- **Filter:** ``$($Module.filter)``"
    $md += "- **Exit Code:** $($Module.exitCode)"
    if ($Module.logFile) {
        $md += "- **Log File:** ``$($Module.logFile)``"
    }
    if ($Module.rawReportDir) {
        $md += "- **Raw Report Dir:** ``$($Module.rawReportDir)``"
    }
    $md += "- **Tests:** $modTotal total, $modPassed passed, $modFailed failed"
    $md += ""

    if ($Module.timedOut) {
        $md += "> **TIMEOUT:** Editor process timed out for this module."
        $md += ""
    }

    if ($modFailed -gt 0) {
        $md += Format-FailedTests -Tests $Module.results.tests
    }

    $md += Format-PassedTests -Tests $Module.results.tests
    return $md -join "`n"
}

function Format-FailedTests {
    param([array]$Tests)

    $failedTests = @($Tests | Where-Object { -not $_.passed })
    if ($failedTests.Count -eq 0) { return "" }

    $md = @()
    $md += "### Failed Tests"
    $md += ""
    foreach ($t in $failedTests) {
        $md += "#### ``$($t.name)``"
        $md += ""
        if ($t.error) {
            $md += '```'
            $md += $t.error
            $md += '```'
            $md += ""
        } else {
            $md += "*No error details captured.*"
            $md += ""
        }
    }
    return $md -join "`n"
}

function Format-PassedTests {
    param([array]$Tests)

    $passedTests = @($Tests | Where-Object { $_.passed })
    if ($passedTests.Count -eq 0) { return "" }

    $md = @()
    $md += "### Passed Tests ($($passedTests.Count))"
    $md += ""
    foreach ($t in $passedTests) {
        $md += "- ``$($t.name)``"
    }
    $md += ""
    return $md -join "`n"
}

# ============================================
# 3. Write Report File
# ============================================
function Write-ReportFile {
    param([string]$Content, [string]$ProjectDir)

    $outputDir = Join-Path $ProjectDir $script:ReportDirName
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    $timestampFile = Get-Date -Format $script:TimestampFormatFile
    $outputFile = Join-Path $outputDir "$timestampFile-autotest-report.md"

    Set-Content -Path $outputFile -Value $Content -Encoding UTF8
    return $outputFile
}

# ============================================
# Main Flow
# ============================================
$resolvedPath = Resolve-ResultsPath -ExplicitPath $ResultsPath -ProjectDirectory $ProjectDir
$results = Get-Content $resolvedPath -Raw | ConvertFrom-Json

$reportContent = Format-TestReport -Data $results -ProjectDir $ProjectDir
$outputFile = Write-ReportFile -Content $reportContent -ProjectDir $ProjectDir

Write-Host "Report saved to: $outputFile" -ForegroundColor Green
