#!/usr/bin/env python3
"""
UE5 自动化测试 Markdown 报告生成器
=============================================
读取 autotest_results.json，生成 Markdown 格式的测试报告。

Usage:
    python report.py --project-dir "D:/Projects/MyGame"
    python report.py --results "path/to/autotest_results.json" --project-dir "D:/Projects/MyGame"
    python report.py -h

Exit codes:
    0   报告生成成功
    1   脚本错误（结果文件未找到等）
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

# ── ANSI 颜色代码 ─────────────────────────────────────────────────────────────
_COLOR_GREEN   = "\033[32m"
_COLOR_RED     = "\033[31m"
_COLOR_RESET   = "\033[0m"


def _color_print(msg: str, color: str = _COLOR_RESET) -> None:
    """如果终端支持，则使用 ANSI 颜色打印。"""
    if sys.stdout.isatty():
        print(f"{color}{msg}{_COLOR_RESET}")
    else:
        print(msg)


def _error_exit(msg: str, code: int = 1) -> None:
    """打印错误信息并以指定退出码终止。"""
    _color_print(msg, _COLOR_RED)
    sys.exit(code)


# ── 常量 ─────────────────────────────────────────────────────────────────────
_RESULTS_FILE_NAME = "autotest_results.json"
_REPORT_DIR_NAME = Path("Saved") / "Automation" / "Reports"
_TIMESTAMP_FORMAT_DISPLAY = "%Y-%m-%d %H:%M:%S"
_TIMESTAMP_FORMAT_FILE = "%Y-%m-%d-%H%M%S"
_REPORT_TITLE = "# UE5 Automation Test Report"
_GENERATOR_CREDIT = "*Generated by ue-autotest skill*"
_DEFAULT_LOG_HINT = "Saved\\Logs"


# ── 1. 解析结果文件路径 ───────────────────────────────────────────────────────
def resolve_results_path(explicit_path: str, project_dir: Path) -> Path:
    """解析结果文件路径：优先显式路径，回退到项目目录下的默认位置。"""
    if explicit_path:
        p = Path(explicit_path)
        if p.exists():
            return p

    auto_path = project_dir / "Saved" / "Automation" / _RESULTS_FILE_NAME
    if auto_path.exists():
        return auto_path

    _error_exit(f"结果文件未找到。尝试过：{explicit_path}，{auto_path}")
    raise SystemExit(1)  # 不可达，但满足类型检查器


# ── 2. 构建 Markdown 报告 ─────────────────────────────────────────────────────
def format_report_header(data: dict[str, Any], project_dir: Path) -> str:
    """生成报告头部（时间戳、项目名、模块数）。"""
    timestamp = datetime.now().strftime(_TIMESTAMP_FORMAT_DISPLAY)
    md = [
        _REPORT_TITLE,
        "",
        f"- **Generated:** {timestamp}",
        f"- **Project:** {project_dir.name}",
        f"- **Modules:** {len(data.get('modules') or [])}",
        "",
    ]
    return "\n".join(md)


def format_summary_section(overall: dict[str, Any]) -> str:
    """生成 Summary 表格。"""
    total = overall.get("total", 0)
    passed = overall.get("passed", 0)
    failed = overall.get("failed", 0)
    pass_rate = round((passed / total) * 100, 1) if total > 0 else 0

    md = [
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Tests | {total} |",
        f"| Passed | {passed} |",
        f"| Failed | {failed} |",
        f"| Pass Rate | {pass_rate}% |",
        "",
    ]

    if failed == 0:
        md.append("> All tests passed.")
    else:
        md.append(f"> **{failed} test(s) failed.**")
    md.append("")
    return "\n".join(md)


def format_failed_tests(tests: list[dict[str, Any]]) -> str:
    """生成 Failed Tests 小节（含围栏错误块）。"""
    failed_tests = [t for t in tests if not t.get("passed")]
    if not failed_tests:
        return ""

    md = ["### Failed Tests", ""]
    for t in failed_tests:
        md.append(f"#### `{t.get('name')}`")
        md.append("")
        if t.get("error"):
            md.append("```")
            md.append(str(t["error"]))
            md.append("```")
            md.append("")
        else:
            md.append("*No error details captured.*")
            md.append("")
    return "\n".join(md)


def format_passed_tests(tests: list[dict[str, Any]]) -> str:
    """生成 Passed Tests 列表小节。"""
    passed_tests = [t for t in tests if t.get("passed")]
    if not passed_tests:
        return ""

    md = [f"### Passed Tests ({len(passed_tests)})", ""]
    for t in passed_tests:
        md.append(f"- `{t.get('name')}`")
    md.append("")
    return "\n".join(md)


def format_module_section(module: dict[str, Any]) -> str:
    """生成单个模块的报告小节。"""
    results = module.get("results") or {}
    summary = results.get("summary") or {}
    tests = results.get("tests") or []
    mod_total = summary.get("total", 0)
    mod_passed = summary.get("passed", 0)
    mod_failed = summary.get("failed", 0)

    md = [
        f"## Module: {module.get('name')}",
        "",
        f"- **Filter:** `{module.get('filter')}`",
        f"- **Exit Code:** {module.get('exitCode')}",
    ]
    if module.get("logFile"):
        md.append(f"- **Log File:** `{module['logFile']}`")
    if module.get("rawReportDir"):
        md.append(f"- **Raw Report Dir:** `{module['rawReportDir']}`")
    md.append(f"- **Tests:** {mod_total} total, {mod_passed} passed, {mod_failed} failed")
    md.append("")

    if module.get("timedOut"):
        md.append("> **TIMEOUT:** Editor process timed out for this module.")
        md.append("")

    if mod_failed > 0:
        md.append(format_failed_tests(tests))

    md.append(format_passed_tests(tests))
    return "\n".join(md)


def format_report_footer() -> str:
    """生成报告脚注。"""
    md = [
        "---",
        "",
        _GENERATOR_CREDIT,
        "",
        f"**Log files:** see each module section; default location is `{_DEFAULT_LOG_HINT}`.",
        "",
    ]
    return "\n".join(md)


def format_test_report(data: dict[str, Any], project_dir: Path) -> str:
    """组装完整 Markdown 报告。"""
    parts = [
        format_report_header(data, project_dir),
        format_summary_section(data.get("overall") or {}),
    ]
    for module in data.get("modules") or []:
        parts.append(format_module_section(module))
    parts.append(format_report_footer())
    return "\n".join(parts)


# ── 3. 写入报告文件 ───────────────────────────────────────────────────────────
def write_report_file(content: str, project_dir: Path) -> Path:
    """将报告写入 Saved/Automation/Reports/<时间戳>-autotest-report.md。"""
    output_dir = project_dir / _REPORT_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp_file = datetime.now().strftime(_TIMESTAMP_FORMAT_FILE)
    output_file = output_dir / f"{timestamp_file}-autotest-report.md"

    output_file.write_text(content, encoding="utf-8")
    return output_file


# ── 主流程 ───────────────────────────────────────────────────────────────────
def main() -> int:
    parser = argparse.ArgumentParser(
        description="从 autotest_results.json 生成 Markdown 测试报告",
        epilog='示例：python report.py --project-dir "D:/Projects/MyGame"',
    )
    parser.add_argument(
        "--results",
        metavar="路径",
        default="",
        help="autotest_results.json 路径（可选，默认从项目目录推断）",
    )
    parser.add_argument(
        "--project-dir",
        metavar="路径",
        default="",
        help="项目根目录",
    )
    args = parser.parse_args()

    project_dir = Path(args.project_dir) if args.project_dir else Path.cwd()

    resolved_path = resolve_results_path(args.results, project_dir)
    try:
        results = json.loads(resolved_path.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, OSError) as exc:
        _error_exit(f"读取/解析结果文件失败：{exc}")
        return 1  # 不可达

    report_content = format_test_report(results, project_dir)
    output_file = write_report_file(report_content, project_dir)

    _color_print(f"报告已保存至：{output_file}", _COLOR_GREEN)
    return 0


if __name__ == "__main__":
    sys.exit(main())
